export const ADMIN_SIGIN_RESPONSE = 'ADMIN_SIGIN_RESPONSE';
export const ADMIN_SIGIN_SUCCESS = 'ADMIN_SIGIN_SUCCESS';
export const ADMIN_SIGIN_ERROR = 'ADMIN_SIGIN_ERROR';
export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';