export const ADD_CART_RESPONSE = 'ADD_CART_RESPONSE';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_ERROR = 'ADD_CART_ERROR';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';