export const ADD_CART_RESPONSE = 'ADD_CART_RESPONSE';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_ERROR = 'ADD_CART_ERROR';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';

export const CART_QTY_UPD_RESPONSE = 'CART_QTY_UPD_RESPONSE';
export const CART_QTY_UPD_SUCCESS = 'CART_QTY_UPD_SUCCESS';
export const CART_QTY_UPD_ERROR = 'CART_QTY_UPD_ERROR';