export const DELIVERY_SIGIN_RESPONSE = 'DELIVERY_SIGIN_RESPONSE';
export const DELIVERY_SIGIN_SUCCESS = 'DELIVERY_SIGIN_SUCCESS';
export const DELIVERY_SIGIN_ERROR = 'DELIVERY_SIGIN_ERROR';
export const DELIVERY_SIGNOUT = 'DELIVERY_SIGNOUT';

export const DELIVERY_SIGNUP_RESPONSE = 'DELIVERY_SIGNUP_RESPONSE';
export const DELIVERY_SIGNUP_SUCCESS = 'DELIVERY_SIGNUP_SUCCESS';
export const DELIVERY_SIGNUP_ERROR = 'DELIVERY_SIGNUP_ERROR';