export const SELLER_SIGIN_RESPONSE = 'SELLER_SIGIN_RESPONSE';
export const SELLER_SIGIN_SUCCESS = 'SELLER_SIGIN_SUCCESS';
export const SELLER_SIGIN_ERROR = 'SELLER_SIGIN_ERROR';
export const SELLER_SIGNOUT = 'SELLER_SIGNOUT';

export const SELLER_SIGNUP_RESPONSE = 'SELLER_SIGNUP_RESPONSE';
export const SELLER_SIGNUP_SUCCESS = 'SELLER_SIGNUP_SUCCESS';
export const SELLER_SIGNUP_ERROR = 'SELLER_SIGNUP_ERROR';