export const USER_SIGIN_RESPONSE = 'USER_SIGIN_RESPONSE';
export const USER_SIGIN_SUCCESS = 'USER_SIGIN_SUCCESS';
export const USER_SIGIN_ERROR = 'USER_SIGIN_ERROR';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_SIGNUP_RESPONSE = 'USER_SIGNUP_RESPONSE';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

export const SMS_SEND_RESPONSE = 'SMS_SEND_RESPONSE'
export const SMS_SEND_SUCCESS = 'SMS_SEND_SUCCESS'
export const SMS_SEND_ERROR = 'SMS_SEND_ERROR'