export const USER_SIGIN_RESPONSE = 'USER_SIGIN_RESPONSE';
export const USER_SIGIN_SUCCESS = 'USER_SIGIN_SUCCESS';
export const USER_SIGIN_ERROR = 'USER_SIGIN_ERROR';
export const USER_SIGNOUT = 'USER_SIGNOUT';